import 'package:flutter/widgets.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'app/app.dart';
import 'features/tasks/data/task_entity.dart';
import 'shared/services/settings_entity.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();

  // Register adapters (generated by build_runner)
  Hive.registerAdapter(TaskEntityAdapter());
  Hive.registerAdapter(SettingsEntityAdapter());

  runApp(const ProviderScope(child: ContextDoApp()));
}
